import { prisma } from "../src/prisma.js";
import { TitleType } from "@prisma/client";

const TEMPLATE_ID = BigInt(103);
const COUNT = 20;

const genres = [
  "Action",
  "Drama",
  "Thriller",
  "Comedy",
  "Sci-Fi",
  "Romance",
  "Adventure",
  "Mystery",
];

const maturityRatings = ["G", "PG", "PG-13", "R", "TV-14", "TV-MA"];

const adjectives = [
  "Crimson",
  "Hidden",
  "Burning",
  "Electric",
  "Silent",
  "Shattered",
  "Wild",
  "Golden",
  "Broken",
  "Sacred",
];

const nouns = [
  "Echo",
  "Legacy",
  "River",
  "Shadow",
  "Path",
  "Promise",
  "Storm",
  "Horizon",
  "Covenant",
  "Whisper",
];

function randomItem<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomName(index: number) {
  const base = `${randomItem(adjectives)} ${randomItem(nouns)}`;
  const suffix = index + 1;
  return `${base} Film ${suffix}`;
}

async function main() {
  const template = await prisma.title.findUnique({
    where: { id: TEMPLATE_ID },
    include: { assetVersions: true },
  });

  if (!template) {
    console.error(`Template title with id ${TEMPLATE_ID.toString()} not found.`);
    process.exit(1);
  }

  console.log(
    `Cloning from template "${template.name}" (${template.id.toString()}) to create ${COUNT} new titles.`,
  );

  for (let i = 0; i < COUNT; i++) {
    const name = randomName(i);
    const existing = await prisma.title.findFirst({ where: { name } });
    if (existing) {
      console.log(`Skipping existing title with name "${name}" (id=${existing.id.toString()}).`);
      continue;
    }

    const primaryGenre = randomItem(genres);
    const extraGenre = Math.random() > 0.5 ? randomItem(genres.filter((g) => g !== primaryGenre)) : null;
    const titleGenres = extraGenre ? [primaryGenre, extraGenre] : [primaryGenre];

    const rating = randomItem(maturityRatings);

    const created = await prisma.title.create({
      data: {
        type: template.type as TitleType,
        name,
        description:
          template.description ??
          "Autogenerated title cloned from template content for testing and catalog filling.",
        genres: titleGenres,
        cast: template.cast,
        crew: template.crew,
        language: template.language ?? "en",
        maturityRating: rating,
        runtimeMinutes: template.runtimeMinutes,
        countryAvailability: template.countryAvailability,
        isOriginal: template.isOriginal,
        releaseDate: template.releaseDate,
        posterUrl: template.posterUrl,
        thumbnailUrl: template.thumbnailUrl,
        trailerUrl: template.trailerUrl,
        previewSpriteUrl: template.previewSpriteUrl,
        previewVttUrl: template.previewVttUrl,
        introStartSec: template.introStartSec,
        introEndSec: template.introEndSec,
        archived: false,
        pendingReview: false,
      },
    });

    if (template.assetVersions?.length) {
      await prisma.assetVersion.createMany({
        data: template.assetVersions.map((av) => ({
          titleId: created.id,
          rendition: av.rendition,
          url: av.url,
          sizeBytes: av.sizeBytes,
          durationSec: av.durationSec,
          status: av.status,
        })),
      });
    }

    console.log(
      `Created cloned title ${created.id.toString()}: "${created.name}" [${primaryGenre}] (${rating}).`,
    );
  }

  console.log("Done cloning template titles.");
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

