export enum Permission {
  DASHBOARD_VIEW = "dashboard:view",
  ADMIN_USERS_MANAGE = "admin:users:manage",
  ADMIN_INVITES_MANAGE = "admin:invites:manage",
  MOVIES_MANAGE = "movies:manage",
  MOVIES_VIEW = "movies:view",
  BLOG_MANAGE = "blog:manage",
  BLOG_VIEW = "blog:view",
  USERS_MANAGE = "users:manage",
  USERS_VIEW = "users:view",
  PAYMENTS_MANAGE = "payments:manage",
  PAYMENTS_VIEW = "payments:view",
  MODERATION_MANAGE = "moderation:manage",
  ANALYTICS_VIEW = "analytics:view",
  SETTINGS_MANAGE = "settings:manage",
  SETTINGS_VIEW = "settings:view",
  OPS_MANAGE = "ops:manage",
}

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(Permission),
  CONTENT_MANAGER: [
    Permission.DASHBOARD_VIEW,
    Permission.MOVIES_MANAGE,
    Permission.BLOG_VIEW,
    Permission.USERS_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.MODERATION_MANAGE,
    Permission.ANALYTICS_VIEW,
    Permission.SETTINGS_VIEW,
    Permission.OPS_MANAGE,
  ],
  BLOG_EDITOR: [
    Permission.DASHBOARD_VIEW,
    Permission.BLOG_MANAGE,
    Permission.MOVIES_VIEW,
    Permission.USERS_VIEW,
    Permission.ANALYTICS_VIEW,
  ],
  MODERATOR: [
    Permission.DASHBOARD_VIEW,
    Permission.MOVIES_VIEW,
    Permission.MODERATION_MANAGE,
    Permission.USERS_MANAGE,
    Permission.ANALYTICS_VIEW,
  ],
  SUPPORT: [
    Permission.DASHBOARD_VIEW,
    Permission.USERS_MANAGE,
    Permission.PAYMENTS_VIEW,
    Permission.MODERATION_MANAGE,
    Permission.ANALYTICS_VIEW,
  ],
  FINANCE: [
    Permission.DASHBOARD_VIEW,
    Permission.PAYMENTS_MANAGE,
    Permission.SETTINGS_MANAGE,
    Permission.ANALYTICS_VIEW,
  ],
  ANALYTICS: [
    Permission.DASHBOARD_VIEW,
    Permission.MOVIES_VIEW,
    Permission.BLOG_VIEW,
    Permission.USERS_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.MODERATION_MANAGE,
    Permission.ANALYTICS_VIEW,
  ],
  OPS: [
    Permission.DASHBOARD_VIEW,
    Permission.SETTINGS_MANAGE,
    Permission.OPS_MANAGE,
    Permission.MOVIES_VIEW,
    Permission.BLOG_VIEW,
    Permission.USERS_VIEW,
    Permission.ANALYTICS_VIEW,
  ],
  USER: [Permission.DASHBOARD_VIEW],
};
