org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dsun.net.inetaddr.ttl=60 -Dsun.net.inetaddr.negative.ttl=0
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.vfs.watch=false
android.useAndroidX=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv6Addresses=false
systemProp.sun.net.inetaddr.ttl=60
systemProp.sun.net.inetaddr.negative.ttl=0
